### ISSUE TITLE
[Feature request] Add project on Zenodo

### ISSUE THREAD

**Issue by npielawski** [DanuserLab/TFM#10]
Hello,

would it be possible to have the project linked on [Zenodo](https://zenodo.org/)?
I am working on a paper and I would like to cite this repository. It would
be much easier if I could add a DOI.

Example of a python project on Zenodo: [https://zenodo.org/record/3467639](https://zenodo.org/record/3467639).

Thanks,
Nicolas

**Comment by DanuserLab** [comment]
Hello Nicolas,

We apologize for the delay. We have just created a DOI for this repository on Zenodo: 10.5281/zenodo.11211836.

Thank you for your patience, and we hope this helps with your paper.

Best regards.
