### ISSUE TITLE
Function or Variant "maxY" can not be identified

### ISSUE THREAD

**Issue by yifanfu01** [DanuserLab/TFM#14]
<img width="600" alt="图片" src="https://github.com/DanuserLab/u-inferforce/assets/85473693/f8c7b3c0-ffc8-4097-8633-ae6acab143e7">
Dear authors,
we applied u-interforce, when running step 1, it occurred.

Version MATLAB2023a, u-interforce latest version.

Many thanks.

**Comment by yifanfu01** [comment]
We addressed temporarily by:

change Line 314: "I = padarray(double(movieData.channels_(iChan).loadImage(j)), [maxY, maxX]);"
to "I =double(movieData.channels_(iChan).loadImage(j));"

it won't report error but we are not clear whether the result is confident.

**Comment by DanuserLab** [comment]
Thanks for your report. This issue has been fixed in the latest release as of on 4/26/2024.
