### ISSUE TITLE
Compiled version of the software

### ISSUE THREAD

**Issue by LAShemilt** [DanuserLab/TFM#15]
Would you be able to provide a compiled version of the software that could be run with the Matlab runtime? 

This would help with being able to containerize this software.

**Comment by DanuserLab** [comment]
Thank you for your request.

We currently do not provide a pre-compiled version of the software. However, you can create a standalone application using the package provided in this repository and the MATLAB Compiler. MATLAB provides resources to help with this process. Please check out the following guide: [Standalone Applications Using MATLAB Compiler](https://www.mathworks.com/support/search.html/videos/getting-started-standalone-applications-using-matlab-compiler-100088.html?fq%5B%5D=asset_type_name:video&fq%5B%5D=category:compiler/standalone-applications&page=1).

We hope this helps.
