### ISSUE TITLE
Please add MATLAB add-ons needed to run this project : )

### ISSUE THREAD

**Issue by ThrobbingNeurons** [DanuserLab/TFM#16]
Only runs with a defined set of add-on added to MATLAB, please can you specify which these are.

**Comment by DanuserLab** [comment]
Thanks for your inquiry. The package uses the following MATLAB toolboxes:
    {'Optimization Toolbox'                   }
    {'Deep Learning Toolbox'                  }
    {'Symbolic Math Toolbox'                  }
    {'Image Processing Toolbox'               }
    {'Statistics and Machine Learning Toolbox'}
    {'Curve Fitting Toolbox'                  }
    {'Parallel Computing Toolbox'             }
